# Generated by Django 5.2.17 on 2026-09-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_stock', models.PositiveIntegerField()),
                ('available_stock', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_stock__gte', 0)), name='drop_total_stock_gte_zero'), models.CheckConstraint(condition=models.Q(('available_stock__gte', 0)), name='drop_available_stock_gte_zero'), models.CheckConstraint(condition=models.Q(('available_stock__lte', models.F('total_stock'))), name='drop_available_stock_lte_total_stock')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='drops.drop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drop', 'status'], name='reservation_drop_status_idx'), models.Index(fields=['expires_at'], name='reservation_expires_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('drop', 'user'), name='unique_active_reservation_per_user_drop')],
            },
        ),
    ]
