# Generated by Django 5.2.17 on 2026-09-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='webhook_event_type_idx'), models.Index(fields=['status'], name='webhook_status_idx'), models.Index(fields=['payment_id'], name='webhook_payment_id_idx'), models.Index(fields=['received_at'], name='webhook_received_at_idx')],
            },
        ),
    ]
